version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=OPORA
          - POSTGRES_PASSWORD=OPORA1
          - POSTGRES_DB=opora
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    upload:
      build:
        context: ./UploadScript
      env_file: docker.env
      
    opora:
      build:
        context: ./Backend
      ports:
        - "8080:5000"
      env_file: docker.env
        
    nginx:
      restart: always
      build:
        context: ./nginx
      ports:
          - "80:80"
